kind: Namespace
apiVersion: v1
metadata:
  name: thefirstcontainer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thefirstcontainer
  labels:
    app: thefirstcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thefirstcontainer
  template:
    metadata:
      labels:
        app: thefirstcontainer
    spec:
      containers:
      - name: thefirstcontainer
        image: tftest/thefirstcontainer
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: thefirstcontainer
spec:
  selector:
    app: thefirstcontainer
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765