apiVersion: apps/v1
kind: Deployment
metadata:
  name: thefirstcontainer
  labels:
    app: thefirstcontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thefirstcontainer
  template:
    metadata:
      labels:
        app: thefirstcontainer
    spec:
      containers:
      - name: thefirstcontainer
        image: teperwoman/thefirstcontainer
        ports:
        - containerPort: 8765